### ISSUE TITLE
Error loading Tests.dll: Unable to load the test container 'Tests.dll' or one of its dependencies. Error details: System.IO.FileLoadException: Could not load file or assembly 'StealFocus.MSTestExtensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=0

### ISSUE THREAD

**Issue by icnocop** [StealFocus/MSTestExtensions#2]
Hi.

After I build MSTestExtensions from the source and add a reference to the Release build configuration, StealFocus.MSTestExtensions.dll, set up a test class that inherits from MSTestExtensionsTestClass and a unit test that uses a custom mstest attribute from a test project, and then run the unit test, the following error occurs:

Error loading C:\TestProject\Tests.dll: Unable to load the test container 'C:\TestProject\Tests.dll' or one of its dependencies. Error details: System.IO.FileLoadException: Could not load file or assembly 'StealFocus.MSTestExtensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=0852b8a0f1458a87' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

I believe this is because StealFocus.MSTestExtensions is delay signed and the private key is missing from the source.

Can a strong name key without a password be added to the source and used for these types of builds so that the assembly doesn't have to be delay signed, for example?

When the nuget package is created, the original strong name key can be used, for example

Thank you.

**Comment by CallumHibbert** [comment]
I thought this project might get some downloads but was not really
expecting contributions.

I have added instructions for building the solution to the Read Me -
https://github.com/StealFocus/MSTestExtensions#building

Callum

**Comment by icnocop** [comment]
Thank you.

Unfortunately, when I built the solution on the command line using Visual Studio's 2010 msbuild.exe and then updated the test project's reference accordingly, I get a different but similar error:

Unable to get type Tests.Tests, Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx. Error: System.IO.FileLoadException: Could not load file or assembly 'StealFocus.MSTestExtensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=0852b8a0f1458a87' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'StealFocus.MSTestExtensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=0852b8a0f1458a87' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestExecuter.GetType(UnitTestElement unitTest, String type)
   at Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestExecuter.ResolveMethods()

Any ideas?

**Comment by icnocop** [comment]
Nevermind, sorry about that.

I just restarted Visual Studio just like the Readme.md indicates and it works now. :)
